cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

olacyvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('products/', include("products.urls")),
    path('cart/', include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

orders/urls.py
from django.urls import path

from .views import OrderCreateView

app_name = "orders"

urlpatterns = [
    path("create/", OrderCreateView.as_view(), name="create"),
]

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

cart/forms.py
from django import forms
from django.conf import settings

PRODUCT_QUANTITY_CHOICES = [
    (i, str(i)) for i in range(1, settings.CART_ITEM_MAX_QUANTITY + 1)
]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        label="Quantidade", choices=PRODUCT_QUANTITY_CHOICES, coerce=int
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from products.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product, quantity=cd["quantity"], override_quantity=cd["override"]
        )

    return redirect("cart:detail")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:detail")


def cart_detail(request):
    cart = Cart(request)
    return render(request, "cart/cart_detail.html", {"cart": cart})

templates/cart/cart_detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Meu Carrinho{% endblock title %}

{% block content %}

<div class="container my-3 table-responsive">
    <h1 class="font-weight-bold">Meu Carrinho</h1>
    {% if cart %}
    <table class="table">
        <thead>
            <tr class="bg-light">
                <th scope="col">Produto</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Preço Unitário</th>
                <th scope="col">Preço Total</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td class="align-middle">
                    <a target="_blank" class="text-decoration-none" href="{{ product.get_absolute_url }}">
                        {{ product.name }}
                    </a>
                </td>
                <td class="align-middle">
                    <form action="{% url 'cart:add' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col">
                                {% render_field item.update_quantity_form.quantity class+="form-control" %}
                            </div>
                            <div class="col">
                                <input class="btn btn-info" type="submit" value="Atualizar">
                            </div>
                        </div>
                        {{ item.update_quantity_form.override }}
                    </form>
                </td>
                <td class="align-middle">R$ {{ item.price }}</td>
                <td class="align-middle">R$ {{ item.total_price }}</td>
                <td class="align-middle text-right">
                    <form action="{% url 'cart:remove' product.id %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="Remover">
                    </form>
                </td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr class="bg-light">
                <td class="font-weight-bold">Total</td>
                <td></td>
                <td></td>
                <td class="font-weight-bold">R$ {{ cart.get_total_price }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    {% else %}
    <p>O carrinho está vazio!</p>
    {% endif %}
    <p class="text-right">
        <a class=" btn btn-primary" href="{% url 'products:list' %}">
            Continuar comprando
        </a>

        <a class="btn btn-success {% if not cart %}disabled{% endif %}" href="{% url 'orders:create' %}">
            Finalizar compra
        </a>
    </p>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}