cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

olacyvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('products/', include("products.urls")),
    path('cart/', include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

payments/urls.py
from django.urls import path

from .views import (
    PaymentCreateView,
    PaymentFailureView,
    PaymentPendingView,
    PaymentSuccessView,
    payment_webhook,
)

app_name = "payments"

urlpatterns = [
    path("process/", PaymentCreateView.as_view(), name="process"),
    path("failure/", PaymentFailureView.as_view(), name="failure"),
    path("pending/", PaymentPendingView.as_view(), name="pending"),
    path("success/", PaymentSuccessView.as_view(), name="success"),
    path("webhook/", payment_webhook, name="webhook"),
]

payments/models.py
from django.db import models
from localflavor.br.models import BRCPFField
from model_utils.models import TimeStampedModel

from orders.models import Order


class Payment(TimeStampedModel):
    order = models.ForeignKey(Order, related_name="payments", on_delete=models.CASCADE)
    transaction_amount = models.DecimalField(
        "Valor da Transação", max_digits=10, decimal_places=2
    )
    installments = models.IntegerField("Parcelas")
    payment_method_id = models.CharField("Método de Pagamento", max_length=250)
    email = models.EmailField()
    doc_number = BRCPFField("CPF")
    mercado_pago_id = models.CharField(max_length=250, blank=True, db_index=True)
    mercado_pago_status = models.CharField(max_length=250, blank=True)
    mercado_pago_status_detail = models.CharField(max_length=250, blank=True)

    class Meta:
        ordering = ("-modified",)

    def __str__(self):
        return f"Pagamento {self.id}"

payments/forms.py
import mercadopago
from django import forms
from django.conf import settings

from .models import Payment


class PaymentForm(forms.ModelForm):
    token = forms.CharField()

    class Meta:
        model = Payment
        fields = [
            "transaction_amount",
            "installments",
            "payment_method_id",
            "email",
            "doc_number",
        ]

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop("order")
        super().__init__(*args, **kwargs)

    def clean_transaction_amount(self):
        transaction_amount = self.cleaned_data["transaction_amount"]
        if float(transaction_amount) != float(self.order.get_total_price()):
            raise forms.ValidationError(
                "O valor da transação não bate com o banco de dados!"
            )
        return transaction_amount

    def save(self):
        cd = self.cleaned_data
        mp = mercadopago.SDK(settings.MERCADO_PAGO_ACCESS_TOKEN)
        payment_data = {
            "transaction_amount": float(self.order.get_total_price()),
            "token": cd["token"],
            "description": self.order.get_description(),
            "installments": cd["installments"],
            "payment_method_id": cd["payment_method_id"],
            "payer": {
                "email": cd["email"],
                "identification": {"type": "CPF", "number": cd["doc_number"]},
            },
        }
        payment = mp.payment().create(payment_data)

        if payment["status"] == 201:
            self.instance.order = self.order
            self.instance.mercado_pago_id = payment["response"]["id"]
            self.instance.mercado_pago_status_detail = payment["response"][
                "status_detail"
            ]
            self.instance.mercado_pago_status = payment["response"]["status"]

            if payment["response"]["status"] == "approved":
                self.order.paid = True
                self.order.save()
            self.instance.save()

        else: 
                print (payment["response"])


class UpdatePaymentForm(forms.Form):
    action = forms.CharField()
    data = forms.JSONField()

    def save(self):
        cd = self.cleaned_data
        mp = mercadopago.SDK(settings.MERCADO_PAGO_ACCESS_TOKEN)
        if cd["action"] == "payment.updated":
            mercado_pago_id = cd["data"]["id"]
            payment = Payment.objects.get(mercado_pago_id=mercado_pago_id)
            payment_mp = mp.payment().get(mercado_pago_id)

            payment.mercado_pago_status = payment_mp["response"]["status"]
            payment.mercado_pago_status_detail = payment_mp["response"]["status_detail"]

            if payment_mp["response"]["status"] == "approved":
                payment.order.paid = True
            else:
                payment.order.paid = False

            payment.order.save()
            payment.save()

payments/views.py
import json

from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils.functional import cached_property
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, TemplateView

from orders.models import Order

from .forms import PaymentForm, UpdatePaymentForm
from .models import Payment


class PaymentCreateView(CreateView):
    model = Payment
    form_class = PaymentForm

    @cached_property
    def order(self):
        order_id = self.request.session.get("order_id")
        order = get_object_or_404(Order, id=order_id)
        return order

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["order"] = self.order
        return form_kwargs

    def form_valid(self, form):
        form.save()
        redirect_url = "payments:failure"
        status = form.instance.mercado_pago_status

        if status == "approved":
            redirect_url = "payments:success"
        if status == "in_process":
            redirect_url = "payments:pending"

        if status and status != "rejected":
            del self.request.session["order_id"]
        return redirect(redirect_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["order"] = self.order
        context["publishable_key"] = settings.MERCADO_PAGO_PUBLIC_KEY
        return context


class PaymentFailureView(TemplateView):
    template_name = "payments/failure.html"


class PaymentPendingView(TemplateView):
    template_name = "payments/pending.html"


class PaymentSuccessView(TemplateView):
    template_name = "payments/success.html"


@csrf_exempt
@require_POST
def payment_webhook(request):
    data = json.loads(request.body)
    form = UpdatePaymentForm(data)
    if form.is_valid():
        form.save()

    return JsonResponse({})

templates/payments/failure.html
{% extends "base.html" %}

{% block title %}Erro{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Pagamento não realizado!</h1>
    <p>
        Alguma coisa aconteceu e o pagamento não foi feito. Tente novamente.
        Se o erro persistir entre em contato conosco.
    </p>
    <a class="btn btn-primary" href="{% url 'payments:process' %}">
        Tentar novamente
    </a>
</div>

{% endblock %}

templates/payments/payment_form.html
{% extends "base.html" %}

{% load static %}

{% block title %}Pagamento com cartão de crédito{% endblock %}

{% block content %}
{% with total_price=order.get_total_price %}

<div class="container my-3">
    <h1 class="font-weight-bold">Pagamento com cartão de crédito</h1>
    <div class="row">
        <div class="col-lg-6">
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endif %}
            <form action="." method="post" id="paymentForm">
                <fieldset class="border-bottom mb-3">
                    <div class="form-group">
                        <label for="email">E-mail</label>
                        <input id="email" name="email" type="text" value="{{ order.email }}" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="docNumber">CPF</label>
                        <input id="docNumber" name="doc_number" data-checkout="docNumber" type="text"
                            value="{{ order.cpf }}" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="cardholderName">Titular do cartão</label>
                        <input id="cardholderName" data-checkout="cardholderName" type="text" class="form-control"
                            value="{{ order.name }}">
                    </div>
                    <div class="form-group">
                        <label for="cardNumber">Número do cartão</label>
                        <input type="text" id="cardNumber" data-checkout="cardNumber" onselectstart="return false"
                            oncopy="return false" oncut="return false" ondrag="return false" ondrop="return false"
                            autocomplete=off class="form-control">
                    </div>
                    <div class="row">
                        <div class="form-group col-6 mb-0">
                            <label for="">Data de vencimento</label>
                            <div class="row">
                                <div class="form-group col-6">
                                    <input type="text" placeholder="MM" id="cardExpirationMonth"
                                        data-checkout="cardExpirationMonth" onselectstart="return false"
                                        onpaste="return false" oncopy="return false" oncut="return false"
                                        ondrag="return false" ondrop="return false" autocomplete=off
                                        class="form-control" maxlength="2">
                                </div>
                                <div class="form-group col-6">
                                    <input type="text" placeholder="YY" id="cardExpirationYear"
                                        data-checkout="cardExpirationYear" onselectstart="return false"
                                        onpaste="return false" oncopy="return false" oncut="return false"
                                        ondrag="return false" ondrop="return false" autocomplete=off
                                        class="form-control" maxlength="2">
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-6">
                            <label for="securityCode">Código de segurança</label>
                            <input id="securityCode" data-checkout="securityCode" type="text"
                                onselectstart="return false" onpaste="return false" oncopy="return false"
                                oncut="return false" ondrag="return false" ondrop="return false" autocomplete=off
                                class="form-control" maxlength="4">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="installments">Parcelas</label>
                        <select type="text" id="installments" name="installments" class="form-control"></select>
                    </div>
                </fieldset>
                <div>
                    <input type="hidden" id="docType" name="docType" data-checkout="docType" type="text"
                        class="form-control" value="CPF" />
                    <input type="hidden" name="payment_method_id" id="paymentMethodId" />
                    <input type="hidden" name="transaction_amount" id="transactionAmount"
                        value="{{ total_price|stringformat:'.2f' }}" />
                    <input type="hidden" id="issuer" name="issuer" data-checkout="issuer" class="form-control" />
                    {% csrf_token %}
                    <button type="submit" class="btn btn-success btn-lg btn-block">Pagar</button>
                    <br>
                </div>
            </form>
        </div>
        <div class="col-lg-6">
            <div class="card border-0 bg-light p-4">
                {% include "order_summary.html" with items=order.items.all total_price=total_price %}
            </div>
        </div>
    </div>
</div>

{% endwith %}
{% endblock %}

{% block script %}
<script src="https://unpkg.com/imask@6.0.7/dist/imask.js"></script>
<script src="https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js"></script>
<script>
    window.Mercadopago.setPublishableKey("{{ publishable_key }}");
</script>
<script src="{% static 'js/process-payment.js' %}"></script>
{% endblock script %}

templates/payments/pending.html
{% extends "base.html" %}

{% block title %}Sucesso!{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Estamos processando o seu pagamento!</h1>
    <p>
        Obrigado por comprar conosco.
        Em até 2 dias úteis você receberá um e-mail com mais informações sobre o pagamento.
    </p>
</div>

{% endblock %}

templates/payments/success.html
{% extends "base.html" %}

{% block title %}Sucesso!{% endblock %}

{% block content %}

<div class="container my-3">
    <h1 class="font-weight-bold">Pagamento efetuado com sucesso!</h1>
    <p>Obrigado por comprar conosco.</p>
</div>

{% endblock %}