cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove

app_name = "cart"

urlpatterns = [
    path("", cart_detail, name="detail"),
    path("add/<int:product_id>/", cart_add, name="add"),
    path("remove/<int:product_id>/", cart_remove, name="remove"),
]

olacyvet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('products/', include("products.urls")),
    path('cart/', include("cart.urls")),
    path("orders/", include("orders.urls")),
    path("payments/", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

pages/urls.py
from django.urls import path

from .views import AboutPageView, HomePageView, TeamPageView, PrimePageView, ServicesPageView, bloodDonationPageView, EmergencyPageView, CancellationPageView, privacyPolicyPageView, DeliveryPageView, temporaryHomePageView

app_name = "pages"

urlpatterns = [
    path("about/", AboutPageView.as_view(), name="about"),
    path("", HomePageView.as_view(), name="home"),
    path("team/", TeamPageView.as_view(), name="team"), 
    path("prime/", PrimePageView.as_view(), name="prime"),
    path("services/", ServicesPageView.as_view(), name="services"),
    path("bloodDonation/", bloodDonationPageView.as_view(), name="bloodDonation"),
    path("emergency/", EmergencyPageView.as_view(), name="emergency"),
    path("cancellation/", CancellationPageView.as_view(), name="cancellation"),
    path("privacyPolicy/", privacyPolicyPageView.as_view(), name="privacyPolicy"),
    path("delivery/", DeliveryPageView.as_view(), name="delivery"),
    path("temporaryHome/", temporaryHomePageView.as_view(), name="temporaryHome"),
    
]

products/urls.py
from django.urls import path

from .views import ProductDetailView, ProductListView

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path("category/<slug:slug>/", ProductListView.as_view(), name="list_by_category"),
]

templates/about.html
{% extends 'base.html' %}

{% block title %}Sobre Nós{% endblock title %}

{% block content %}
{% load static %}
<br><br><br>
<div align="center" >
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Nós somos a Clínica Olacy's Vet</h1>
      <p class="lead my-3"><strong>A Clinica Veterinária Olacy's Vet tem como compromisso oferecer os melhores recursos em Medicina Veterinária para seu animal de estimação. Fundada em 28 de setembro de 2020, busca oferecer aos proprietários dos animais a segurança de um tratamento competente, ético e acima de tudo um compromisso de muito respeito e dedicação aos animais.</strong></strong></p>
      <p class="lead my-3"><strong>Para isso contamos com uma estrutura privilegiada no Bairro Parque Tamandaré, trazendo sempre aprimoramento para atendimento qualificado para seu animal de estimação e para isso contamos com uma equipe de especialistas nas mais diversas áreas da Medicina Veterinária de Cães e Gatos, formada por médicos veterinários capacitados experientes e em constante atualização.</strong></p>
      <br>
      <img src="https://assets.website-files.com/5ce2e8de2575f27cdf7815f1/5e1635e3546baa82ad81a907_GettyImages-529116816.jpg">
    </div>
  </div>
  <br><br>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">

{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <link rel="shortcut icon" href="{% static 'images/olacy_vet_icon.svg' %}" type="image/x-icon" />
    <title>{% block title %}Olacy's Vet{% endblock title %}</title>
</head>

  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-sm py-3 border-bottom navbar-light">
        <div class="container">
            <a href="{% url 'pages:home' %}" class="navbar-brand">
                <span class="font-weight-bold h3">Olacy's Vet</span>
            </a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li>
                      <li class="nav-item">
                        <a href="{% url 'pages:home' %}" class="nav-link lead mr-4 font-weight-bold">Home</a>
                    </li>
                    <li>
                      <li class="nav-item">
                        <a href="{% url 'pages:prime' %}" class="nav-link lead mr-4 font-weight-bold">Prime</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'products:list' %}" class="nav-link lead mr-4 font-weight-bold">Produtos</a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'cart:detail' %}" class="nav-link lead mr-4 font-weight-bold">Meu Carrinho</a>
                  </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link lead mr-4 font-weight-bold nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Quem Somos</a>
                      <div class="dropdown-menu" aria-labelledby="dropdown01">
                      <a class="dropdown-item" href="{% url 'pages:about' %}">Sobre Nós</a>
                      <a class="dropdown-item" href="{% url 'pages:team' %}">Equipe</a>
                      <a class="dropdown-item" href="{% url 'pages:services' %}">Serviços</a>
                    </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
        {% block script %}
        {% endblock script %}

</body>

<footer>
    <hr class="featurette-divider">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <img alt="tel_image" width="200" height="100" data-sticky-width="150" data-sticky-height="40" src="{% static 'images/OlacyVet_icon.jpg' %}">
              <p>
                Av. Pelinca, 410 - Parque Tamandaré<br>
                ,Campos dos Goytacazes<br>
                <a href="https://www.instagram.com/olacyrodrigues/"> <img src = "{% static 'images/instagram_icon.svg' %}" alt="Instagram_Icon"/></a>
                <a href="https://www.facebook.com"><img src = "{% static 'images/facebook_icon.svg' %}" alt="Facebook_Icon"/></a>
                <a href="https://www.linkedin.com/in/olacy-rodrigues-449a03170/"><img src = "{% static 'images/linkedin_icon.svg' %}" alt="Linkedin_icon"/></a>
                <a href="https://github.com/olacyrodrigues"><img src = "{% static 'images/Github_icon.svg' %}" alt="Github_icon"/></a>
              </p>

            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Links Úteis</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:home' %}">Inicio</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:about' %}">Sobre nós</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:team' %}">equipe</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Fale conosco</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Nossos Serviços</h4>
            <ul>
             
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:prime' %}">Prime</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:services' %}">Serviços</a></li>
            </ul>
          </div>

            <div class="col-lg-3 col-md-6 footer-links">
            <h4>Ajuda</h4>
            <ul>
             
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:delivery' %}">Entregas</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:cancellation' %}">Cancelamentos</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'pages:privacyPolicy' %}">Política de privacidade</a></li>
            </ul>
          </div>
 
        </div>
      </div>
    </div>
    <div align="center" class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Olacy's Vet</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer>

</html>

templates/cancellation.html
{% extends 'base.html' %}
{% block title %}Cancelamentos{% endblock title %}

{% block content %}
{% load static %}

<br><br>

<section id="services" class="services services">
    <div class="container" data-aos="fade-up">

      <div align="center" class="section-title">
        <h1 class="display-4 font-italic">Olacy's Vet | Cancelamentos, Trocas e Devoluções de Mercadorias </h1>
        <br><br>
      </div>
  <div>
  <p class="lead my-3"><strong><b> 1. Cancelamentos de pedidos</b> serão aceitos com <b>total reembolso</b> dos valores pagos se ainda <b>não despachados.</b></strong></p>
  </div>
  <div>
   <p class="lead my-3"><strong><b> 2.</b> serão aceitos com Em casos de <b>troca</b> ou <b>devolução</b> de mercadorias já despachadas, o produto deve ser reencaminhado para nossa loja física sem que sua embalagem tenha sido violada, com todos os acessórios dentro de 7 (sete) dias. A Olacy's vet deve ser notificada imediatamente para que possa auxiliá-lo no procedimento de troca. O reembolso será efetuado subtraindo-se as despesas de frete.<b> A devolução de produtos com embalagem violada ou com sinais de uso não será aceita.</b></strong></p>
  </div>
  <div>
  <p class="lead my-3"><strong><b> 3.</b> Caso algum produto tenha sido﻿ <b>expedido por engano</b>, esteja em <b>desacordo com o pedido, avariado</b> e/ou <b>danificado durante o transporte</b>, entre em contato conosco. Se for comprovada a nossa falha ou problemas no transporte, faremos a troca do(s) produto(s) enviado(s) erroneamente ou o estorno de todos os valores pagos, <b>inclusive de frete</b>. Mas é fundamental que, antes de realizar a devolução,<b> entre em contato conosco para repassarmos as devidas orientações.</b></strong></p>
  </div>
  <div>
  <p class="lead my-3"><strong><b> 4.</b> No caso dos produtos <b>Sob Encomenda (personalizados)</b>, o cancelamento será possível em até <b>1 (um) dia útil</b> após a confirmação de pagamento. Após esse período, o produto personalizado não poderá ser cancelado, trocado ou devolvido.</strong></p>
  </div>
  <div>
  <p class="lead my-3"><strong><b> 5.</b> Para devolução de produtos de pronta entrega já despachados pela Olacy's vet e que enquadrem-se no caráter de <b>Desistência</b> por parte do cliente, ele deverá arcar com custos de frete para devolução. A mercadoria deve ser <b>devolvida em sua embalagem original, inviolada.</b> O estorno/cancelamento do pagamento só será efetivado <b>após o recebimento da mercadoria por parte da empresa.</b></strong></p>
  </div>
  <div>
  <p class="lead my-3"><strong><b> 6.</b> Neste caso, o produto devolvido deverá se encontrar em perfeito estado, com todas as peças, opcionais munidos de manuais (se houverem). Se detectado o uso do produto ou avaria, a Olacy's vet não aceitara o produto de volta.</strong></p>
  </div><br>
  <div>
  <p class="lead my-3"><strong><b>Para quaisquer outros problemas detectados, favor entrar em contato conosco para lhe orientarmos sobre os procedimentos corretos a serem adotados.</b></strong></p>
  </div>

  </section>

{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block title %}Olacy's Vet{% endblock title %}

{% block content %}
{% load static %}



<link rel="stylesheet" href="{% static 'css/carousel.css' %}" />
<link rel="stylesheet" href="{% static 'css/cards.css' %}" />

<main>
    <div class="container-fluid">
      <div id="mainSlider" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#mainSlider" data-slide-to="0" class="active"></li>
          <li data-target="#mainSlider" data-slide-to="1"></li>
          <li data-target="#mainSlider" data-slide-to="2"></li>
         </ol> 
         <div class="carousel-inner">
           <div class="carousel-item active">
             <img src="{% static 'images/banner_1.png' %}" class="d-block w100" alt="olacysvet">
             <div class="carousel-caption d-none d-md-block">
             </div>
           </div>
            <div class="carousel-item">
             <img src="{% static 'images/banner_2.png' %}" class="d-block w100" alt="olacysvet">
             <div class="carousel-caption d-none d-md-block">
             </div>
           </div>
            <div class="carousel-item">
             <img src="{% static 'images/banner_3.png' %}" class="d-block w100" alt="Conheça nossas especialidades">
             <div class="carousel-caption d-none d-md-block">
               <h2>Conheça nossas especialidades</h2>
               <p>Nossas Especialidades Veterinárias Atualmente e equipe do Olacy's Vet Hospital Veterinário 24 horas é composta por...</p>
               <a href="{% url 'pages:services' %}" class="main-btn">saiba mais.</a>
             </div>
           </div>
          
         <a href="#mainSlider" class="carousel-control-prev" role="button" data-slide= "prev">
           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
           <span class="sr-only">Anterior</span>
         </a>
        <a href="#mainSlider" class="carousel-control-next" role="button" data-slide= "next">
           <span class="carousel-control-next-icon" aria-hidden="true"></span>
           <span class="sr-only">Próxmo</span>
         </a>
      </div>
    </div>
  </main>
<br><br>

<section id="cards">
  <div class="container">
    <div class="card">
    <div class="imgBx">
    <img src="{% static 'images/doe_sangue_card.png' %}"> 
    </div>
    <div class="content">
      <h2>Salve um amigo</h2>
      <p>é super importante a doação de sangue para salvar a vida de uma pessoa e com os pets isso não é diferente. Afinal, animais podem doar sangue e ajudar o outro.</p>
      <p><a class="btn btn-secondary" href="{% url 'pages:bloodDonation' %}" role="button">Saiba Mais.</a></p>
    </div>
    </div>
    <div class="card">
    <div class="imgBx">
    <img src="{% static 'images/primeiro_socorro_card.jpg' %}"> 
    </div>
    <div class="content">
      <h2>Primeiros Socorros</h2>
      <p>É extremamente importante estar preparado para possíveis emergências que possam ocorrer com seu melhor amigo</p>
      <p><a class="btn btn-secondary" href="{% url 'pages:emergency' %}" role="button">Saiba Mais.</a></p>
    </div>
    </div>
    <div class="card">
    <div class="imgBx">
    <img src="{% static '/images/lar_temporario.jpg' %}"> 
    </div>
    <div class="content">
      <h2>Lar temporário</h2>
      <p>Conheça a importância e os benefícios de oferecer um lar temporário para animais</p>
      <p><a class="btn btn-secondary" href="{% url 'pages:temporaryHome' %}" role="button">Saiba Mais.</a></p>
    </div>
    </div>
  </div>
</section>

<hr class="featurette-divider">

<section id="scroll">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="https://portalfacilarquivos.blob.core.windows.net/uploads/PIRANGA/imgOrig/%7B4EDEEE63-ED23-0A1E-5BBC-C4CE61E58BC1%7D.jpeg" alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="featurette-heading">Você sabia? <span class="text-muted"><br>Os pets não transmitem COVID-19</span></h2>
                    <p>A Organização Mundial da Saúde (OMS) está monitorando pesquisas sobre a relação entre animais de estimação e a Covid-19, doença causada pelo novo coronavírus. Até o momento, não há evidência significativa de que animais de estimação possam ficar doentes ou transmitir a doença.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 2-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <div class="p-5"><img class="img-fluid rounded-circle" src="https://veja.abril.com.br/wp-content/uploads/2016/05/alx_guia-veja-cachorros-20141217-004_original1.jpeg?quality=70&strip=info&resize=680,453" alt="..." /></div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="featurette-heading">Como identificar se seu cão está sentindo dor?<span class="text-muted"><br>mantenha-se atento!</span></h2>
                    <p>Engasgar, chacoalhar a cabeça e rebolar são exemplos de sinais que podem indicar algum tipo de dor. Confira se seu animalzinho não está sofrendo em silêncio. Além de evitar o sofrimento prolongado, o diagnóstico precoce só traz benefícios. Afinal, é mais fácil e eficiente tratar doenças em estágio inicial.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 3-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'images/dogbox.png' %}" alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="featurette-heading">Já soube da novidade? <span class="text-muted"><br>Chegou as caixas surpresas da Olacy's Vet!</span></h2>
                    <p>Faça uma assinatura mensal ou anual e receba todo mês em sua casa uma caixa cheia de surpresas para seu bichinho.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="contact" class="contact">
    <div align="center" class="container">

      <div class="section-title">
        <h2>Fale conosco</h2>
        <p>Nosso endereço, contato e área para nos enviar uma mensagem.</p>
      </div>

    </div>
   
    <div>
        <center>
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14822.58580693424!2d-41.338481!3d-21.755228!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x4e08696779d4b337!2sSaturn%C3%A1lia%20Club!5e0!3m2!1spt-BR!2sbr!4v1601329251425!5m2!1spt-BR!2sbr" width="1100" height="600" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe></center>
    </div>
    
    <div class="container">

      <div class="row mt-5">

        <div class="col-lg-6">
          <div class="row">
            <div class="col-md-12">
              <div  align="center" class="info-box">
                <i class="bx bx-map"></i>
                 <img alt="local" width="40" height="40" data-sticky-width="150" data-sticky-height="40" src="https://anossamesa.org/wp-content/uploads/2020/07/106165.png">
                <h3>Endereço</h3>
                <p>Av. Pelinca, 410 - Parque Tamandaré, Campos dos Goytacazes <br>- Rio de Janeiro, 28035-053</p>
              </div>
            </div>
            <div align="center" class="col-md-6">
              <div class="info-box mt-4">
                <i class="bx bx-envelope"></i>
                 <img alt="email_image" width="37" height="37" data-sticky-width="150" data-sticky-height="40" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQTw-GLH6M52Kief_yTcTWzDKeQIkNd7qZCfg&usqp=CAU">
                <h3>Email</h3>
                <p>olacy.vet@gmail.com<br>sac@olacysvet.com.br</p>
              </div>
            </div>
            <div align="center" class="col-md-6">
              <div class="info-box mt-4">
                <i class="bx bx:phone-call"></i>
                <img alt="tel_image" width="37" height="37" data-sticky-width="150" data-sticky-height="40" src="https://imagensemoldes.com.br/wp-content/uploads/2020/12/Desenho-Icone-Telefone-PNG-1024x1024.png">
                <h3>Telefone</h3>
                <p>(22) 1-2345-6789 <br>(22) 9-8765-4321</p>
              </div>
            </div>
          </div>
        </center>
        </div>
  <div>
    <img class="featurette-image img-fluid mx-auto" src="{% static 'images/vet_rua.png' %}" data-src="holder.js/500x500/auto" alt="Generic placeholder image" width="550" height="700">
    
  </div>
{% endblock content %}

templates/order_summary.html
<div class="card border-0 bg-light p-4">
    <h4>Resumo do Pedido</h4>
    <ul class="list-group list-group-flush">
        {% for item in items %}
        <li class="list-group-item bg-light">
            {{ item.quantity }}x {{ item.product.name }}
            <span class="float-right">R$ {{ item.total_price }}{{ item.get_total_price }}</span>
        </li>
        {% endfor %}
        <li class="font-weight-bold list-group-item bg-light">Total
            <span class="float-right">R$ {{ total_price }}</span>
        </li>
    </ul>
</div>

templates/pagination.html
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    Página {{ page.number }} de {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Próxima</a>
    {% endif %}
</div>

templates/prime.html
{% extends 'base.html' %}

{% block title %}Prime{% endblock title %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/prime.css' %}" />

<br><br>
<section class="page-section" id="services">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">O prime</h2>
            <h3 class="section-subheading text-muted">Chegou!!!!</h3>
        </div>
        <br><br><br>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <img class="rounded-circle" src="https://box.petiko.com.br/images/dogs-petiko.png" alt="Generic placeholder image" width="140" height="140">
                <h4 class="my-3">Desmonstre seu amor</h4>
                <p class="text-muted">Com o prime você recebe mensalmente itens e brinquedos voltados para seu pet</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <img class="rounded-circle" src="https://box.petiko.com.br/images/caixa-petiko.png" alt="Generic placeholder image" width="140" height="140">
                <h4 class="my-3">Escolha</h4>
                <p class="text-muted">lanos mensais, semestrais e anuais. Aqui você tem a garantia de que o valor dos itens sempre valerão mais do que o valor pago. Assinaturas a partir de R$ 79,90/mês</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <img class="rounded-circle" src="https://box.petiko.com.br/images/presente-petiko.png" alt="Generic placeholder image" width="140" height="140">
                <h4 class="my-3">Presenteie</h4>
                <p class="text-muted">Agora a melhor hora: Todos os meses você receberá um kit especialmente selecionado para seu cachorro contendo de 7 a 8 itens.</p>
            </div>
        </div>
    </div>
</section>
<br>
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-upper">Quer ainda mais vantagens?</span>
                        <span class="section-heading-lower">Então toma!</span>
                    </h2>
                    <ul>
                        <li>5% de desconto em todas as consultas na Clínica Olacy's Vet</li>
                        <li>Programa de indicação: Você ganha R$50,00 para gastar na Olacy's Vet</li> 
                        <p>para cada amigo que você convidar para fazer parte do Prime</p></li>
                        </ul>
                        
                </div>
            </div>
        </div>
    </div>
</section>
<section class="about">
    <div class="main">
        <img src="https://i.imgur.com/V9OrM0r.jpg">
        <div class="about-text">
            <h3>Gostou do prime?</h3>
            <p>Não perca essa oportunidade e compre para receber essa caixa de surpresas recheadas com itens para seu peludinho.</p>
            <button type="button" onclick="window.location.href ='{% url 'products:list' %}'" >Comprar</button>
        </div>
    </div>
</section>


{% endblock content %}